name: ci
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
                cache: 'npm'
            - run: npm install
            - run: npm run build
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
                cache: 'npm'
            - run: npm install
            - run: npx tsc --noEmit
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
                cache: 'npm'
            - run: npm install
            - run: npm run test
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
                cache: 'npm'
            - run: npm install
            - run: npm run lint
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
                cache: 'npm'
            - run: npm install
            - run: npm run check-prettier
